### ISSUE TITLE
Mention to slack error in itms-legacy-import-utility

### ISSUE THREAD

**Issue by Rodrigo-J-Damasceno** [abeyuya/actions-mention-to-slack#269]
se the error below
Error: Request failed with status code 504
    at createError (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.6/dist/index.js:736:15)
    at settle (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.6/dist/index.js:12997:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.6/dist/index.js:13765:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by abeyuya** [comment]
If you still have trouble, please re-open the issue.
