### ISSUE TITLE
メンションが存在しないコメントの場合に、エラーとなります

### ISSUE THREAD

**Issue by tmf16** [abeyuya/actions-mention-to-slack#6]
on: `pull_request_review`

```
TypeError: Cannot read property 'match' of null
    at Object.module.exports.559.exports.pickupUsername (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:12814:23)
    at Object.module.exports.131.exports.execNormalMention (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:2905:38)
    at Object.module.exports.131.exports.main (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:2952:23)
    at Object.325 (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:6470:8)
    at __webpack_require__ (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:37:19)
    at /home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/abeyuya/actions-mention-to-slack/v2.3/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by abeyuya** [comment]
@tmf16 修正しました！
v2.4をリリースしたので、そちらに更新してご確認頂けると

https://github.com/abeyuya/actions-mention-to-slack/releases/tag/v2.4
